import type { EnvironmentVariable } from './environment-variables-types';

export const environmentVariables = [
  {
    name: 'SERVER_PORT',
    slug: 'server-port',
    category: 'Aplicação',
    required: false,
    type: 'integer',
    defaultValue: 8084,
    description: [['Porta do listener HTTP. A aplicação escuta em ', { code: ':SERVER_PORT' }, '. O padrão é ', { code: '8084' }, '.']],
  },
  {
    name: 'LOG_LEVEL',
    slug: 'log-level',
    category: 'Logs e observabilidade',
    required: false,
    type: 'enum',
    defaultValue: 'info',
    example: 'trace',
    allowedValues: ['trace', 'debug', 'info', 'warn', 'error', 'fatal', 'panic', 'disabled'],
    description: [
      [
        'Nível global do Zerolog. Valores aceitos: ',
        { code: 'trace' },
        ', ',
        { code: 'debug' },
        ', ',
        { code: 'info' },
        ', ',
        { code: 'warn' },
        ', ',
        { code: 'error' },
        ', ',
        { code: 'fatal' },
        ', ',
        { code: 'panic' },
        ', ',
        { code: 'disabled' },
        '. O padrão é ',
        { code: 'info' },
        '.',
      ],
    ],
  },
  {
    name: 'DATABASE_URL',
    slug: 'database-url',
    category: 'Banco de dados',
    required: true,
    type: 'url',
    example: 'postgres://...',
    description: [['String de conexão com o PostgreSQL.']],
  },
  {
    name: 'DATABASE_SAVE_DATA_NEW_MESSAGE',
    slug: 'database-save-data-new-message',
    category: 'Banco de dados',
    required: false,
    type: 'boolean',
    defaultValue: true,
    description: [
      [
        'Habilita a persistência de linhas WhatsApp ',
        { code: 'Message' },
        ' a partir de eventos de mensagens recebidas. O padrão é ',
        { code: 'true' },
        '.',
      ],
    ],
  },
  {
    name: 'DATABASE_SAVE_MESSAGE_UPDATE',
    slug: 'database-save-message-update',
    category: 'Banco de dados',
    required: false,
    type: 'boolean',
    defaultValue: false,
    description: [
      [
        'Habilita a persistência de eventos de recibo do WhatsApp em ',
        { code: 'MessageUpdate' },
        '. O padrão é ',
        { code: 'false' },
        '.',
      ],
    ],
  },
  {
    name: 'DATABASE_SAVE_DATA_CONTACTS',
    slug: 'database-save-data-contacts',
    category: 'Banco de dados',
    required: false,
    type: 'boolean',
    defaultValue: false,
    description: [
      [
        'Habilita a persistência de sincronização e eventos de contatos do WhatsApp em ',
        { code: 'Contact' },
        '. O padrão é ',
        { code: 'false' },
        '.',
      ],
    ],
  },
  {
    name: 'WHATSAPP_SESSION_STORE',
    slug: 'whatsapp-session-store',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'enum',
    defaultValue: 'postgres',
    allowedValues: ['sqlite', 'postgres'],
    description: [
      [
        'Banco usado pelo whatsmeow para sessões e dispositivos. Valores aceitos: ',
        { code: 'sqlite' },
        ', ',
        { code: 'postgres' },
        '. O padrão é ',
        { code: 'postgres' },
        ' quando não for definido.',
      ],
    ],
  },
  {
    name: 'WHATSAPP_SESSION_SQLITE_DSN',
    slug: 'whatsapp-session-sqlite-dsn',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'string',
    defaultValue: 'file:./data/whatsmeow.db?_foreign_keys=on',
    description: [
      [
        'DSN do SQLite usado somente quando ',
        { code: 'WHATSAPP_SESSION_STORE=sqlite' },
        '. As chaves estrangeiras precisam continuar habilitadas.',
      ],
    ],
  },
  {
    name: 'WHATSAPP_SESSION_POSTGRES_URL',
    slug: 'whatsapp-session-postgres-url',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'url',
    example: 'postgres://...',
    description: [
      [
        'String de conexão opcional e dedicada do PostgreSQL para as sessões do whatsmeow. Quando vazia, ',
        { code: 'DATABASE_URL' },
        ' é usada pelo SQL store do whatsmeow.',
      ],
    ],
  },
  {
    name: 'WEBHOOK_GLOBAL_URL',
    slug: 'webhook-global-url',
    category: 'Webhooks',
    required: false,
    type: 'url',
    example: 'https://example.com/webhook',
    description: [
      [
        'URL do webhook global. Precisa ser ',
        { code: 'http' },
        ' ou ',
        { code: 'https' },
        ' absoluta; obrigatória somente quando ',
        { code: 'WEBHOOK_GLOBAL_ENABLED=true' },
        '.',
      ],
    ],
  },
  {
    name: 'WEBHOOK_GLOBAL_ENABLED',
    slug: 'webhook-global-enabled',
    category: 'Webhooks',
    required: false,
    type: 'boolean',
    defaultValue: false,
    allowedValues: [true, false, 'vazio'],
    description: [
      [
        'Habilita o envio de todos os eventos reconhecidos de todas as instâncias para ',
        { code: 'WEBHOOK_GLOBAL_URL' },
        '. O padrão é ',
        { code: 'false' },
        '.',
      ],
    ],
  },
  {
    name: 'WEBSOCKET_ENABLED',
    slug: 'websocket-enabled',
    category: 'WebSocket',
    required: false,
    type: 'boolean',
    defaultValue: true,
    description: [['Habilita as rotas ', { code: '/ws/instance/events' }, ' e ', { code: '/ws/global/events' }, '. O padrão é ', { code: 'true' }, '.']],
  },
  {
    name: 'WEBSOCKET_ALLOWED_ORIGINS',
    slug: 'websocket-allowed-origins',
    category: 'WebSocket',
    required: false,
    type: 'string',
    example: 'http://localhost:3000,http://localhost:5173',
    description: [['Lista separada por vírgula de origens aceitas para browsers. Quando vazia, clientes com ', { code: 'Origin' }, ' são rejeitados.']],
  },
  {
    name: 'WEBSOCKET_ALLOW_EMPTY_ORIGIN',
    slug: 'websocket-allow-empty-origin',
    category: 'WebSocket',
    required: false,
    type: 'boolean',
    defaultValue: true,
    description: [['Permite clientes backend sem header ', { code: 'Origin' }, '.']],
  },
  {
    name: 'WEBSOCKET_PING_INTERVAL',
    slug: 'websocket-ping-interval',
    category: 'WebSocket',
    required: false,
    type: 'duration',
    defaultValue: '25s',
    unit: 'duration',
    description: [['Intervalo de ping do servidor WebSocket.']],
  },
  {
    name: 'WEBSOCKET_PONG_TIMEOUT',
    slug: 'websocket-pong-timeout',
    category: 'WebSocket',
    required: false,
    type: 'duration',
    defaultValue: '60s',
    unit: 'duration',
    description: [['Prazo máximo para receber pong antes de encerrar a conexão.']],
  },
  {
    name: 'WEBSOCKET_WRITE_TIMEOUT',
    slug: 'websocket-write-timeout',
    category: 'WebSocket',
    required: false,
    type: 'duration',
    defaultValue: '10s',
    unit: 'duration',
    description: [['Prazo máximo de escrita de frames.']],
  },
  {
    name: 'WEBSOCKET_SEND_BUFFER',
    slug: 'websocket-send-buffer',
    category: 'WebSocket',
    required: false,
    type: 'integer',
    defaultValue: 256,
    description: [['Tamanho do buffer por cliente WebSocket.']],
  },
  {
    name: 'AUTHENTICATION_JWT_EXPIRES_IN',
    slug: 'authentication-jwt-expires-in',
    category: 'Autenticação',
    required: true,
    type: 'integer',
    example: 3600,
    unit: 'segundos',
    description: [['Expiração do JWT em segundos. O valor ', { code: '0' }, ' remove a claim ', { code: 'exp' }, '.']],
  },
  {
    name: 'AUTHENTICATION_JWT_SECRET',
    slug: 'authentication-jwt-secret',
    category: 'Autenticação',
    required: true,
    type: 'string',
    example: 'strong-secret',
    description: [['Chave secreta usada para assinar JWTs com HS256.']],
  },
  {
    name: 'AUTHENTICATION_GLOBAL_AUTH_TOKEN',
    slug: 'authentication-global-auth-token',
    category: 'Autenticação',
    required: true,
    type: 'string',
    example: 'admin-token',
    description: [['Token usado somente para criar e listar instâncias.']],
  },
  {
    name: 'QRCODE_LIMIT',
    slug: 'qrcode-limit',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 5,
    description: [['Número máximo de QR codes servidos durante uma tentativa de pareamento.']],
  },
  {
    name: 'QRCODE_EXPIRATION_TIME',
    slug: 'qrcode-expiration-time',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 30,
    unit: 'segundos',
    description: [['Tempo máximo de vida do QR code em segundos.']],
  },
  {
    name: 'QRCODE_LIGHT_COLOR',
    slug: 'qrcode-light-color',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'string',
    example: '#ffffff',
    description: [['Cor clara usada na geração do QR PNG.']],
  },
  {
    name: 'QRCODE_DARK_COLOR',
    slug: 'qrcode-dark-color',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'string',
    example: '#198754',
    description: [['Cor escura usada na geração do QR PNG.']],
  },
  {
    name: 'CONFIG_SESSION_PHONE_CLIENT',
    slug: 'config-session-phone-client',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'enum',
    defaultValue: 'DESKTOP',
    allowedValues: [
      'ALOHA',
      'ANDROID_AMBIGUOUS',
      'ANDROID_PHONE',
      'ANDROID_TABLET',
      'AR_DEVICE',
      'AR_WRIST',
      'CATALINA',
      'CHROME',
      'CLOUD_API',
      'DESKTOP',
      'EDGE',
      'FIREFOX',
      'IE',
      'IOS_CATALYST',
      'IOS_PHONE',
      'IPAD',
      'OHANA',
      'OPERA',
      'SAFARI',
      'SMARTGLASSES',
      'TCL_TV',
      'UWP',
      'VR',
      'WEAR_OS',
    ],
    description: [
      [
        'Tipo de plataforma exibido nos dispositivos conectados do WhatsApp. O padrão é ',
        { code: 'DESKTOP' },
        ' quando não for definido.',
      ],
    ],
  },
  {
    name: 'CONFIG_SESSION_PHONE_NAME',
    slug: 'config-session-phone-name',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'string',
    defaultValue: 'CodeChat',
    description: [['Nome do sistema ou cliente exibido nos dispositivos conectados do WhatsApp. O padrão é ', { code: 'CodeChat' }, '.']],
  },
  {
    name: 'WHATSAPP_PAIRING_TIMEOUT',
    slug: 'whatsapp-pairing-timeout',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'duration',
    defaultValue: '3m',
    unit: 'duration',
    description: [['Timeout total do contexto de pareamento por QR. O padrão é ', { code: '3m' }, ' quando não for definido.']],
  },
  {
    name: 'WHATSAPP_AUTO_RECONNECT',
    slug: 'whatsapp-auto-reconnect',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'boolean',
    example: true,
    description: [['Habilita a restauração, na inicialização, das sessões que deveriam estar online.']],
  },
  {
    name: 'WHATSAPP_STARTUP_RECONNECT_CONCURRENCY',
    slug: 'whatsapp-startup-reconnect-concurrency',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 5,
    description: [['Número máximo de sessões WhatsApp restauradas em paralelo.']],
  },
  {
    name: 'WHATSAPP_CONNECT_TIMEOUT',
    slug: 'whatsapp-connect-timeout',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 30,
    unit: 'segundos',
    description: [['Timeout inicial de espera da conexão, em segundos.']],
  },
  {
    name: 'WHATSAPP_RECONNECT_INITIAL_DELAY',
    slug: 'whatsapp-reconnect-initial-delay',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 2,
    unit: 'segundos',
    description: [['Backoff inicial de reconexão, em segundos.']],
  },
  {
    name: 'WHATSAPP_RECONNECT_MAX_DELAY',
    slug: 'whatsapp-reconnect-max-delay',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 60,
    unit: 'segundos',
    description: [['Backoff máximo de reconexão, em segundos.']],
  },
  {
    name: 'WHATSAPP_PROFILE_PICTURE_TIMEOUT',
    slug: 'whatsapp-profile-picture-timeout',
    category: 'WhatsApp e sessão',
    required: true,
    type: 'integer',
    example: 15,
    unit: 'segundos',
    description: [['Timeout para buscar foto de perfil, em segundos.']],
  },
  {
    name: 'WHATSAPP_ADDRESS_CACHE_TTL',
    slug: 'whatsapp-address-cache-ttl',
    category: 'WhatsApp e sessão',
    required: false,
    type: 'duration',
    defaultValue: '168h',
    unit: 'duration',
    description: [['TTL dos mapeamentos em cache entre endereço WhatsApp e JID canônico. O padrão é ', { code: '168h' }, '.']],
  },
  {
    name: 'MESSAGE_PROCESSING_WORKERS',
    slug: 'message-processing-workers',
    category: 'Aplicação',
    required: false,
    type: 'integer',
    defaultValue: 4,
    description: [['Número máximo de jobs assíncronos de mensagem processados em paralelo. O padrão é ', { code: '4' }, '.']],
  },
  {
    name: 'MESSAGE_PROCESSING_QUEUE_SIZE',
    slug: 'message-processing-queue-size',
    category: 'Aplicação',
    required: false,
    type: 'integer',
    defaultValue: 100,
    description: [
      [
        'Número máximo de jobs assíncronos de mensagem aguardando em memória. O padrão é ',
        { code: '100' },
        '; os valores precisam ser maiores que zero.',
      ],
    ],
  },
  {
    name: 'MESSAGE_PROCESSING_TIMEOUT',
    slug: 'message-processing-timeout',
    category: 'Aplicação',
    required: false,
    type: 'duration',
    defaultValue: '60s',
    unit: 'duration',
    description: [['Timeout total para um job assíncrono de mensagem. O padrão é ', { code: '60s' }, '.']],
  },
  {
    name: 'MESSAGE_GROUP_INFO_TIMEOUT',
    slug: 'message-group-info-timeout',
    category: 'Aplicação',
    required: false,
    type: 'duration',
    defaultValue: '30s',
    unit: 'duration',
    description: [
      [
        'Timeout para carregar informações e participantes de grupo do WhatsApp durante o processamento de ',
        { code: 'mentionAll' },
        '. O padrão é ',
        { code: '30s' },
        '.',
      ],
    ],
  },
  {
    name: 'MESSAGE_SEND_TIMEOUT',
    slug: 'message-send-timeout',
    category: 'Aplicação',
    required: false,
    type: 'duration',
    defaultValue: '30s',
    unit: 'duration',
    description: [['Timeout para presença/delay e envio final pelo WhatsApp durante o processamento assíncrono de mensagem. O padrão é ', { code: '30s' }, '.']],
  },
  {
    name: 'MESSAGE_BATCH_WORKER_ENABLED',
    slug: 'message-batch-worker-enabled',
    category: 'Message Batch',
    required: false,
    type: 'boolean',
    defaultValue: true,
    description: [
      [
        'Habilita o worker persistente de Envio em lote. Com ',
        { code: 'false' },
        ', os endpoints e os dados continuam disponíveis, mas nenhum item é consumido.',
      ],
    ],
  },
  {
    name: 'MESSAGE_BATCH_WORKER_POLL_INTERVAL_MS',
    slug: 'message-batch-worker-poll-interval-ms',
    category: 'Message Batch',
    required: false,
    type: 'integer',
    defaultValue: 1000,
    unit: 'milissegundos',
    description: [['Intervalo, em milissegundos, entre consultas do worker e da outbox. Precisa ser maior que zero.']],
  },
  {
    name: 'MESSAGE_BATCH_INSTANCE_RECHECK_INTERVAL_MS',
    slug: 'message-batch-instance-recheck-interval-ms',
    category: 'Message Batch',
    required: false,
    type: 'integer',
    defaultValue: 5000,
    unit: 'milissegundos',
    description: [['Intervalo, em milissegundos, para reavaliar instâncias de lotes em ', { code: 'WAITING_FOR_INSTANCE' }, '.']],
  },
  {
    name: 'MESSAGE_BATCH_MAX_DELAY_MS',
    slug: 'message-batch-max-delay-ms',
    category: 'Message Batch',
    required: false,
    type: 'integer',
    defaultValue: 86400000,
    unit: 'milissegundos',
    description: [['Maior ', { code: 'options.delay.maxMs' }, ' aceito na criação de um lote; o padrão equivale a 24 horas.']],
  },
  {
    name: 'MESSAGE_BATCH_MAX_RECIPIENTS',
    slug: 'message-batch-max-recipients',
    category: 'Message Batch',
    required: false,
    type: 'integer',
    defaultValue: 10000,
    description: [['Limite de entradas recebidas em ', { code: 'recipients' }, ' por lote, antes da remoção de duplicidades.']],
  },
  {
    name: 'MESSAGE_BATCH_SHUTDOWN_TIMEOUT_MS',
    slug: 'message-batch-shutdown-timeout-ms',
    category: 'Message Batch',
    required: false,
    type: 'integer',
    defaultValue: 15000,
    unit: 'milissegundos',
    description: [
      [
        'Tempo máximo, em milissegundos, para envios já iniciados terminarem durante o shutdown antes de serem tratados como ',
        { code: 'UNKNOWN' },
        '.',
      ],
    ],
  },
  {
    name: 'MESSAGE_BATCH_TIMEZONE',
    slug: 'message-batch-timezone',
    category: 'Message Batch',
    required: false,
    type: 'string',
    defaultValue: 'UTC',
    description: [['Timezone IANA padrão para agendas de lote que omitem ', { code: 'schedule.timezone' }, '.']],
  },
  {
    name: 'MEDIA_PRE_UPLOAD_MAX_FILE_SIZE',
    slug: 'media-pre-upload-max-file-size',
    category: 'Mídias',
    required: false,
    type: 'string',
    defaultValue: '100MB',
    description: [
      [
        'Tamanho máximo aceito em ',
        { code: 'POST /instance/:instance/media/uploads' },
        '. O padrão é ',
        { code: '100MB' },
        '; valores maiores são rejeitados antes de carregar o arquivo inteiro em memória.',
      ],
    ],
  },
] satisfies readonly EnvironmentVariable[];
